In [ ]:
!pip install spacy
!pip install spacymoji

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: spacy in /usr/local/lib/python3.7/dist-packages (3.4.1)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.0.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (21.3)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.0.6)
Requirement already satisfied: thinc<8.2.0,>=8.1.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (8.1.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.9 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.0.10)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.21.6)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.4.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.23.0)
Requirement already satisfied: pathy>=0.3.5 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.6.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (4.64.1)
Requirement already satisfied: typer<0.5.0,>=0.3.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.11.3)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.0.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from spacy) (57.4.0)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.0.8)
Requirement already satisfied: typing-extensions<4.2.0,>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy) (4.1.1)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.0.8)
Requirement already satisfied: wasabi<1.1.0,>=0.9.1 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.10.1)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.10.0,>=1.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.9.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.3.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from catalogue<2.1.0,>=2.0.6->spacy) (3.8.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->spacy) (3.0.9)
Requirement already satisfied: smart-open<6.0.0,>=5.2.1 in /usr/local/lib/python3.7/dist-packages (from pathy>=0.3.5->spacy) (5.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2022.9.24)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (1.24.3)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.7/dist-packages (from thinc<8.2.0,>=8.1.0->spacy) (0.7.8)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.7/dist-packages (from thinc<8.2.0,>=8.1.0->spacy) (0.0.2)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.7/dist-packages (from typer<0.5.0,>=0.3.0->spacy) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->spacy) (2.0.1)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: spacymoji in /usr/local/lib/python3.7/dist-packages (3.0.1)
Requirement already satisfied: emoji<1.0.0,>=0.4.5 in /usr/local/lib/python3.7/dist-packages (from spacymoji) (0.6.0)
Requirement already satisfied: spacy<4.0.0,>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from spacymoji) (3.4.1)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (1.21.6)
Requirement already satisfied: typing-extensions<4.2.0,>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (4.1.1)
Requirement already satisfied: wasabi<1.1.0,>=0.9.1 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (0.10.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (2.23.0)
Requirement already satisfied: typer<0.5.0,>=0.3.0 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (0.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (2.11.3)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (1.0.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (2.0.8)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.9 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (3.0.10)
Requirement already satisfied: pathy>=0.3.5 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (0.6.2)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (2.4.4)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (2.0.6)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (1.0.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.10.0,>=1.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (1.9.2)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (3.0.7)
Requirement already satisfied: thinc<8.2.0,>=8.1.0 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (8.1.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (4.64.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (3.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (21.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from spacy<4.0.0,>=3.0.0->spacymoji) (57.4.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from catalogue<2.1.0,>=2.0.6->spacy<4.0.0,>=3.0.0->spacymoji) (3.8.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->spacy<4.0.0,>=3.0.0->spacymoji) (3.0.9)
Requirement already satisfied: smart-open<6.0.0,>=5.2.1 in /usr/local/lib/python3.7/dist-packages (from pathy>=0.3.5->spacy<4.0.0,>=3.0.0->spacymoji) (5.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<4.0.0,>=3.0.0->spacymoji) (2022.9.24)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<4.0.0,>=3.0.0->spacymoji) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<4.0.0,>=3.0.0->spacymoji) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<4.0.0,>=3.0.0->spacymoji) (1.24.3)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.7/dist-packages (from thinc<8.2.0,>=8.1.0->spacy<4.0.0,>=3.0.0->spacymoji) (0.7.8)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.7/dist-packages (from thinc<8.2.0,>=8.1.0->spacy<4.0.0,>=3.0.0->spacymoji) (0.0.2)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.7/dist-packages (from typer<0.5.0,>=0.3.0->spacy<4.0.0,>=3.0.0->spacymoji) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->spacy<4.0.0,>=3.0.0->spacymoji) (2.0.1)

In [ ]:
import pandas as pd
import re
import spacy
from spacymoji import Emoji

In [ ]:
nlp = spacy.load("en_core_web_sm")
emoji = Emoji(nlp)
nlp.add_pipe("emoji", first=True)

In [ ]:
df_ayam = pd.read_csv("dataset-ayam.csv")

In [ ]:
df_ayam

,Title,Ingredients,URL
0,Ayam Woku Manado,1 Ekor Ayam Kampung (potong 12)--2 Buah Jeruk ...,/id/resep/4473027-ayam-woku-manado
1,Ayam goreng tulang lunak,1 kg ayam (dipotong sesuai selera jangan kecil...,/id/resep/4471956-ayam-goreng-tulang-lunak
2,Ayam cabai kawin,1/4 kg ayam--3 buah cabai hijau besar--7 buah ...,/id/resep/4473057-ayam-cabai-kawin
3,Minyak Ayam,400 gr kulit ayam & lemaknya--8 siung bawang p...,/id/resep/4427438-minyak-ayam
4,Nasi Bakar Ayam,"1 piring nasi--¹/⁴ fillet ayam, potong kotak, ...",/id/resep/4472552-nasi-bakar-ayam
...,...,...,...
1790,Nugget ayam simpel,400 gram ayam giling--1 lembar roti tawar kupa...,/id/resep/4308989-nugget-ayam-simpel
1791,Ukepan Ayam,1/2 kg ayam--6 siung bawang merah--6 siung baw...,/id/resep/4289253-ukepan-ayam
1792,Chicken Stroganoff with Mushroom,"Fillet ayam, cuci bersih & lumuri sedikit tepu...",/id/resep/4308032-chicken-stroganoff-with-mush...
1793,Sop Pangsit Ayam,1/4 kg dada ayam--1 buah jeruk nipis--2 cm Jah...,/id/resep/4308088-sop-pangsit-ayam
1794,Ayam Bumbu Bawang,"1 dada ayam fillet, cuci bersih, potong kecil2...",/id/resep/4308575-ayam-bumbu-bawang

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_ayam1 = df_ayam['Title'].apply(extract_emojies)

emoji_counts = (emojies_df_ayam1
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

  Emoji  Count
0     👍      1
1     🐔      1
2     🍲      1
3     😋      1
4     🔥      1
5     😊      1
6     😍      1
7     😂      1
8     🍗      1
9     😁      2

In [ ]:
df_ayam['Title'] = df_ayam['Title'].str.replace('[^a-zA-z0-9.,!?/:;\"\'\s]', '', flags=re.UNICODE)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

In [ ]:
df_ayam['Title']

0                       Ayam Woku Manado
1               Ayam goreng tulang lunak
2                       Ayam cabai kawin
3                            Minyak Ayam
4                        Nasi Bakar Ayam
                      ...
1790                  Nugget ayam simpel
1791                         Ukepan Ayam
1792    Chicken Stroganoff with Mushroom
1793                    Sop Pangsit Ayam
1794                   Ayam Bumbu Bawang
Name: Title, Length: 1795, dtype: object

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_ayam1c = df_ayam['Title'].apply(extract_emojies)

emoji_counts = (emojies_df_ayam1c
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
df_ayam['Ingredients']= df_ayam['Ingredients'].astype(str)

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_ayam1 = df_ayam['Ingredients'].apply(extract_emojies)

emoji_counts = (emojies_df_ayam1
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

  Emoji  Count
0     ▪      1
1     😊      1
2     😍      1
3     🌶      1
4     ➖      3
5     ➡      4

In [ ]:
df_ayam['Ingredients'] = df_ayam['Ingredients'].str.replace('[^a-zA-z0-9.,!?/:;\"\'\s]', '', flags=re.UNICODE)
df_ayam['Ingredients']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

0       1 Ekor Ayam Kampung potong 122 Buah Jeruk Nipi...
1       1 kg ayam dipotong sesuai selera jangan kecil2...
2       1/4 kg ayam3 buah cabai hijau besar7 buah caba...
3       400 gr kulit ayam  lemaknya8 siung bawang puti...
4       1 piring nasi/ fillet ayam, potong kotak, cuci...
                              ...
1790    400 gram ayam giling1 lembar roti tawar kupas2...
1791    1/2 kg ayam6 siung bawang merah6 siung bawang ...
1792    Fillet ayam, cuci bersih  lumuri sedikit tepun...
1793    1/4 kg dada ayam1 buah jeruk nipis2 cm Jahe ge...
1794    1 dada ayam fillet, cuci bersih, potong kecil2...
Name: Ingredients, Length: 1795, dtype: object

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_ayam2c = df_ayam['Ingredients'].apply(extract_emojies)

emoji_counts = (emojies_df_ayam2c
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_ayam1 = df_ayam['URL'].apply(extract_emojies)

emoji_counts = (emojies_df_ayam1
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
df_ikan = pd.read_csv("dataset-ikan.csv")

In [ ]:
df_ikan

,Title,Ingredients,URL
0,Ikan Kembung Bakar Teflon,"1/2 kg ikan kembung sate, bersihkan--1 buah je...",/id/resep/4474225-ikan-kembung-bakar-teflon
1,Mujaer asam pedas manis,1/2 kg ikan mujaer (stok gurame habis)--2 buah...,/id/resep/4473689-mujaer-asam-pedas-manis
2,Gurame Asam manis,1/2 kg ikan gurame--2 buah wortel (potong sepe...,/id/resep/4473428-gurame-asam-manis
3,Asam padeh ikan tuna,1/2 kg ikan tuna--6 siung bawang merah--4 siun...,/id/resep/4473138-asam-padeh-ikan-tuna
4,Avocado Tuna Salad,1 kaleng Tuna Chunks--2 butir telur rebus--3 b...,/id/resep/4473223-avocado-tuna-salad
...,...,...,...
1813,Mie rebus tongkol suwir ala neng tika,1 bungkus mie rebus (kari ayam)--2 potong ikan...,/id/resep/4003324-mie-rebus-tongkol-suwir-ala-...
1814,Tongkol pecak sambel korek ala neng tika,1 ekor ikan tongkol (potong kecil cuci bersih)...,/id/resep/4001241-tongkol-pecak-sambel-korek-a...
1815,Lele frozen berbumbu,1 kg lele isi 10--Bumbu rendam:--1 sdt garam--...,/id/resep/4002895-lele-frozen-berbumbu
1816,Gurami saus padang,Gurami--1 buah Jeruk nipis--Garam--Lada--3 siu...,/id/resep/4002591-gurami-saus-padang
1817,Kepala Kakap Masak Kuning,1 buah Kepala Kakap--Bumbu :--Sesuai selera Ca...,/id/resep/4001893-kepala-kakap-masak-kuning

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_ikan1 = df_ikan['Title'].apply(extract_emojies)

emoji_counts = (emojies_df_ikan1
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_ikan2 = df_ikan['Ingredients'].apply(extract_emojies)

emoji_counts = (emojies_df_ikan2
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

  Emoji  Count
0     😊      1
1     😘      1
2     ❤      1
3     👆      1
4     😆      1
5     👉      1
6     ▪      2
7     🌶      3

In [ ]:
df_ikan['Ingredients'] = df_ikan['Ingredients'].str.replace('[^a-zA-z0-9.,!?/:;\"\'\s]', '', flags=re.UNICODE)
df_ikan['Ingredients']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

0       1/2 kg ikan kembung sate, bersihkan1 buah jeru...
1       1/2 kg ikan mujaer stok gurame habis2 buah Wor...
2       1/2 kg ikan gurame2 buah wortel potong seperti...
3       1/2 kg ikan tuna6 siung bawang merah4 siung ba...
4       1 kaleng Tuna Chunks2 butir telur rebus3 buah ...
                              ...
1813    1 bungkus mie rebus kari ayam2 potong ikan ton...
1814    1 ekor ikan tongkol potong kecil cuci bersihBa...
1815    1 kg lele isi 10Bumbu rendam:1 sdt garam1 sdt ...
1816    Gurami1 buah Jeruk nipisGaramLada3 siung Bawan...
1817    1 buah Kepala KakapBumbu :Sesuai selera Cabe M...
Name: Ingredients, Length: 1818, dtype: object

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_ikan2c = df_ikan['Ingredients'].apply(extract_emojies)

emoji_counts = (emojies_df_ikan2c
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_ikan3 = df_ikan['URL'].apply(extract_emojies)

emoji_counts = (emojies_df_ikan3
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
df_kambing = pd.read_csv("dataset-kambing.csv")

In [ ]:
df_kambing

,Title,Ingredients,URL
0,.Sate Kambing,Bahan-bahan :--500 gr Daging kambing--Daun pep...,/id/resep/4470066-sate-kambing
1,Rabeg Kambing,1 kg daging kambing bagian paha beserta tulang...,/id/resep/4469170-rabeg-kambing
2,Gulai kambing,500 gram daging kambing--Bumbu :--sesuai seler...,/id/resep/4467084-gulai-kambing
3,Sayur tulang kambing,1.5 kg tulang sumsum kambing(direbus dahulu)ag...,/id/resep/4458778-sayur-tulang-kambing
4,Sate Kambing,300 garam daging kambing--1/2 buah jeruk nipis...,/id/resep/4462884-sate-kambing
...,...,...,...
1722,Beef Bowl / rice Bowl ala yoshinoya,100 gr daging sapi / kambing iris tipis--1 bua...,/id/resep/1345995-beef-bowl-rice-bowl-ala-yosh...
1723,Nasi Kebuli,"2 cup beras,enakan pake yg mawur--1/4 kg dagin...",/id/resep/1342740-nasi-kebuli
1724,Tengkleng solo,Bumbu halus :--bawang merah--bawang putih--ser...,/id/resep/1313808-tengkleng-solo
1725,Tongseng,500-700 gr daging kambing/sapi--1 sachet santa...,/id/resep/1047280-tongseng
1726,Yogurt Handmade,1 L susu murni (hewani lebih baik)--35 mL star...,/id/resep/1309172-yogurt-handmade

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_kambing1 = df_kambing['Title'].apply(extract_emojies)

emoji_counts = (emojies_df_kambing1
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

  Emoji  Count
0     🐐      1
1    🇮🇳      1

In [ ]:
df_kambing['Title'] = df_kambing['Title'].str.replace('[^a-zA-z0-9.,!?/:;\"\'\s]', '', flags=re.UNICODE)
df_kambing['Title']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

0                             .Sate Kambing
1                             Rabeg Kambing
2                             Gulai kambing
3                      Sayur tulang kambing
4                              Sate Kambing
                       ...
1722    Beef Bowl / rice Bowl ala yoshinoya
1723                            Nasi Kebuli
1724                         Tengkleng solo
1725                               Tongseng
1726                        Yogurt Handmade
Name: Title, Length: 1727, dtype: object

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_kambing1c = df_kambing['Title'].apply(extract_emojies)

emoji_counts = (emojies_df_kambing1c
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
df_kambing['Ingredients']= df_kambing['Ingredients'].astype(str)

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_kambing2 = df_kambing['Ingredients'].apply(extract_emojies)

emoji_counts = (emojies_df_kambing2
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

   Emoji  Count
0      ❄      1
1      👌      1
2      🍰      1
3      🍛      1
4      🍚      1
5      😉      1
6      😍      1
7      ▶      1
8      😀      1
9      ✒      1
10     🍨      1
11     👍      1
12     😝      1
13     🐑      2
14     🍅      2
15     🌶      2
16     😄      2
17     🍃      2
18     😁      2
19     ✔      2
20     😂      2
21     🐐      2
22     ☘      2
23     🍥      3
24     👇      4

In [ ]:
df_kambing['Ingredients'] = df_kambing['Ingredients'].str.replace('[^a-zA-z0-9.,!?/:;\"\'\s]', '', flags=re.UNICODE)
df_kambing['Ingredients']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

0       Bahanbahan :500 gr Daging kambingDaun pepayaBu...
1       1 kg daging kambing bagian paha beserta tulang...
2       500 gram daging kambingBumbu :sesuai selera Sa...
3       1.5 kg tulang sumsum kambingdirebus dahuluagar...
4       300 garam daging kambing1/2 buah jeruk nipisse...
                              ...
1722    100 gr daging sapi / kambing iris tipis1 buah ...
1723    2 cup beras,enakan pake yg mawur1/4 kg daging ...
1724    Bumbu halus :bawang merahbawang putihserehleng...
1725    500700 gr daging kambing/sapi1 sachet santan k...
1726    1 L susu murni hewani lebih baik35 mL starter ...
Name: Ingredients, Length: 1727, dtype: object

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_kambing2c = df_kambing['Ingredients'].apply(extract_emojies)

emoji_counts = (emojies_df_kambing2c
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_kambing3 = df_kambing['URL'].apply(extract_emojies)

emoji_counts = (emojies_df_kambing3
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
df_sapi = pd.read_csv("dataset-sapi.csv")

In [ ]:
df_sapi

,Title,Ingredients,URL
0,Beef Teriyaki,250 gr daging sapi--1 siung bawang bombai--5 s...,/id/resep/4473529-beef-teriyaki
1,Rendang Sapi,1 kg daging sapi--4 butir kelapa untuk 2L sant...,/id/resep/4473035-rendang-sapi
2,Tongseng daging sapi pedas,300 gr daging sapi (iris tipis panjang)--Bumbu...,/id/resep/4472871-tongseng-daging-sapi-pedas
3,Semur Daging Sapi,1/2 kg daging sapi--1 biji bawang bombay--2 si...,/id/resep/4472987-semur-daging-sapi
4,Tongseng daging sapi,500 gram Daging sapi--Santan (boleh pakai kara...,/id/resep/4472530-tongseng-daging-sapi
...,...,...,...
1761,Oseng kikil sapi pedas manis,500 gr kikil sapi (saya potong persegi panjang...,/id/resep/3361881-oseng-kikil-sapi-pedas-manis
1762,Bistik sapi empuk. Dengan tips memasak daging ...,1/2 kg daging sapi. Potong tipis melebar. Cuci...,/id/resep/3362180-bistik-sapi-empuk-dengan-tip...
1763,Tongseng Daging Sapi,500 gr daging sapi (rebus hingga empuk)--1 rua...,/id/resep/3361383-tongseng-daging-sapi
1764,Sayur godog Iga sapi,1/2 kg iga sapi--3 buah wortel--5 buah buncis-...,/id/resep/3361681-sayur-godog-iga-sapi
1765,Sup daging sapi,1 kg daging sapi rebus--3 buah wortel iris2 ag...,/id/resep/3361918-sup-daging-sapi

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_sapi1 = df_sapi['Title'].apply(extract_emojies)

emoji_counts = (emojies_df_sapi1
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
df_sapi['Ingredients']= df_sapi['Ingredients'].astype(str)

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_sapi2 = df_sapi['Ingredients'].apply(extract_emojies)

emoji_counts = (emojies_df_sapi2
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

   Emoji  Count
0      🐮      1
1      ✔      1
2      🍥      1
3      😉      1
4      😊      1
5      😁      1
6      👌      2
7      ⬇      2
8      💥      2
9      🌶      2
10     🍀      2
11     ▪      4
12     🍽      4

In [ ]:
df_sapi['Ingredients'] = df_sapi['Ingredients'].str.replace('[^a-zA-z0-9.,!?/:;\"\'\s]', '', flags=re.UNICODE)
df_sapi['Ingredients']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

0       250 gr daging sapi1 siung bawang bombai5 siung...
1       1 kg daging sapi4 butir kelapa untuk 2L santan...
2       300 gr daging sapi iris tipis panjangBumbu hal...
3       1/2 kg daging sapi1 biji bawang bombay2 siung ...
4       500 gram Daging sapiSantan boleh pakai kara 1 ...
                              ...
1761    500 gr kikil sapi saya potong persegi panjang ...
1762    1/2 kg daging sapi. Potong tipis melebar. Cuci...
1763    500 gr daging sapi rebus hingga empuk1 ruas le...
1764    1/2 kg iga sapi3 buah wortel5 buah buncis2 bua...
1765    1 kg daging sapi rebus3 buah wortel iris2 agak...
Name: Ingredients, Length: 1766, dtype: object

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_sapi2c = df_sapi['Ingredients'].apply(extract_emojies)

emoji_counts = (emojies_df_sapi2c
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_sapi3 = df_sapi['URL'].apply(extract_emojies)

emoji_counts = (emojies_df_sapi3
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
df_tahu = pd.read_csv("dataset-tahu.csv")

In [ ]:
df_tahu

,Title,Ingredients,URL
0,Martabak tahu pedas kulit lumpia,12 lembar kulit lumpia--4 buah tahu putih--2 b...,/id/resep/4472701-martabak-tahu-pedas-kulit-lu...
1,Batagor (Bakso Tahu Goreng) ala rumahan anti g...,Bahan batagor--3 kotak ukuran kecil tahu kunin...,/id/resep/4473611-batagor-bakso-tahu-goreng-al...
2,Sayur Sutace (sop tahu ceker),1/2 kg ceker ayam--4 buah wortel ukuran sedang...,/id/resep/4473647-sayur-sutace-sop-tahu-ceker
3,TTKK (tahu telur timun tauge kuah kacang),1 butir telur--1 tahu--secukupnya Timun--secuk...,/id/resep/4473231-ttkk-tahu-telur-timun-tauge-...
4,Perkedel Tahu Wortel Sederhana,1 bks tahu putih--1 batang wortel (potong keci...,/id/resep/4473213-perkedel-tahu-wortel-sederhana
...,...,...,...
1837,Ayam siram tahu,Bahan ayam tepung :--250 gr dada ayam filet--1...,/id/resep/4038046-ayam-siram-tahu
1838,Tumis Tauge Tahu,"2 buah tahu (potong dadu, goreng stengah maten...",/id/resep/4038315-tumis-tauge-tahu
1839,Tahu KW DEBM,4 butir telur--1 santan segitiga--1 bks agar2 ...,/id/resep/4037785-tahu-kw-debm
1840,Tahu goreng krispi simple,4 buah tahu putih (goreng terlebih dahulu sete...,/id/resep/4037870-tahu-goreng-krispi-simple
1841,Tahu masak kuning,"5 buah tahu putih, potong segitiga--1 ikat kac...",/id/resep/4037967-tahu-masak-kuning

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_tahu1 = df_tahu['Title'].apply(extract_emojies)

emoji_counts = (emojies_df_tahu1
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

  Emoji  Count
0    ☺️      1
1    🇮🇩      1

In [ ]:
df_tahu['Title'] = df_tahu['Title'].str.replace('[^a-zA-z0-9.,!?/:;\"\'\s]', '', flags=re.UNICODE)
df_tahu['Title']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

0                       Martabak tahu pedas kulit lumpia
1       Batagor Bakso Tahu Goreng ala rumahan anti gagal
2                            Sayur Sutace sop tahu ceker
3                TTKK tahu telur timun tauge kuah kacang
4                         Perkedel Tahu Wortel Sederhana
                              ...
1837                                     Ayam siram tahu
1838                                    Tumis Tauge Tahu
1839                                        Tahu KW DEBM
1840                           Tahu goreng krispi simple
1841                                   Tahu masak kuning
Name: Title, Length: 1842, dtype: object

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_tahu1c = df_tahu['Title'].apply(extract_emojies)

emoji_counts = (emojies_df_tahu1c
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_tahu2 = df_tahu['Ingredients'].apply(extract_emojies)

emoji_counts = (emojies_df_tahu2
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

  Emoji  Count
0     😀      1
1     👉      1
2     🌸      1
3     😁      1
4     🌶      1
5     🍤      1
6     🎯      6

In [ ]:
df_tahu['Ingredients'] = df_tahu['Ingredients'].str.replace('[^a-zA-z0-9.,!?/:;\"\'\s]', '', flags=re.UNICODE)
df_tahu['Ingredients']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

0       12 lembar kulit lumpia4 buah tahu putih2 batan...
1       Bahan batagor3 kotak ukuran kecil tahu kuning5...
2       1/2 kg ceker ayam4 buah wortel ukuran sedang6 ...
3       1 butir telur1 tahusecukupnya Timunsecukupnya ...
4       1 bks tahu putih1 batang wortel potong kecilke...
                              ...
1837    Bahan ayam tepung :250 gr dada ayam filet1 but...
1838    2 buah tahu potong dadu, goreng stengah mateng...
1839    4 butir telur1 santan segitiga1 bks agar2 plai...
1840    4 buah tahu putih goreng terlebih dahulu seten...
1841    5 buah tahu putih, potong segitiga1 ikat kacan...
Name: Ingredients, Length: 1842, dtype: object

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_tahu2c = df_tahu['Ingredients'].apply(extract_emojies)

emoji_counts = (emojies_df_tahu2c
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_tahu3 = df_tahu['URL'].apply(extract_emojies)

emoji_counts = (emojies_df_tahu3
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
df_telur = pd.read_csv("dataset-telur.csv")

In [ ]:
df_telur

,Title,Ingredients,URL
0,Orak arik telur buncis,1 buah telur--10 buncis--3 bawang merah--2 baw...,/id/resep/4474114-orak-arik-telur-buncis
1,Terik ayam tempe telor,4 sayap ayam--4 buah telor--1/2 papan tempe--B...,/id/resep/4474066-terik-ayam-tempe-telor
2,Telur Kornet,1/2 kaleng kornet--2-3 buah bawang prei--2 bua...,/id/resep/4473838-telur-kornet
3,Tahu telur surabaya,1 butir telur--1 potong tahu putih goreng sete...,/id/resep/4473784-tahu-telur-surabaya
4,Telur ceplok masak kecap,4 butir telur--4 siung bwng merah--2 siung bwn...,/id/resep/4473512-telur-ceplok-masak-kecap
...,...,...,...
1969,Telur rebus isi (filling boiled eggs),6 butir telur--10 grm paprika kuning--2 sendok...,/id/resep/3885560-telur-rebus-isi-filling-boil...
1970,Tempe goreng telur,"1 papan tempe, kukus--1 butir telur ayam--1 ba...",/id/resep/3875271-tempe-goreng-telur
1971,Pindang Telur,5 buah telur rebus yg telah dikupas--1 buah te...,/id/resep/3885479-pindang-telur
1972,"Sup tomat dan telur,menu sederhana",2 buah tomat--1 potong tahu halus (nen tofu)--...,/id/resep/3885509-sup-tomat-dan-telurmenu-sede...
1973,Dadar Telur Cah Toge,"3 Butir Telur, kocok lepas--3 Siung Bawang mer...",/id/resep/3884008-dadar-telur-cah-toge

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_telur1 = df_telur['Title'].apply(extract_emojies)

emoji_counts = (emojies_df_telur1
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

   Emoji  Count
0      🍽      1
1      🌯      1
2      🥘      1
3      🍱      1
4      🍆      1
5      😆      1
6      🌿      1
7      😛      1
8      🔥      1
9      🥗      1
10     🥚      1
11     😈      1
12     🦑      1
13     🍒      1
14   👩‍🍳      1
15     💞      1
16     🍟      1
17     🥕      1
18     🌟      1
19     🍄      2
20     😊      2
21     😅      2
22     🍁      2
23     🍔      2
24     🌰      2
25     💓      2
26     😤      3
27     🌶      3
28     😉      3
29     😍      3
30     ☺      4
31     😘      5
32     😂      5
33     🐣      5
34     👌      6
35     😁      6
36     😄      7
37     👍      8
38     😋      9
39     🍳     19

In [ ]:
df_telur['Title'] = df_telur['Title'].str.replace('[^a-zA-z0-9.,!?/:;\"\'\s]', '', flags=re.UNICODE)
df_telur['Title']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

0                    Orak arik telur buncis
1                    Terik ayam tempe telor
2                              Telur Kornet
3                       Tahu telur surabaya
4                  Telur ceplok masak kecap
                       ...
1969    Telur rebus isi filling boiled eggs
1970                     Tempe goreng telur
1971                          Pindang Telur
1972     Sup tomat dan telur,menu sederhana
1973                   Dadar Telur Cah Toge
Name: Title, Length: 1974, dtype: object

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_telur1c = df_telur['Title'].apply(extract_emojies)

emoji_counts = (emojies_df_telur1c
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
df_telur['Ingredients']= df_telur['Ingredients'].astype(str)

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_telur2 = df_telur['Ingredients'].apply(extract_emojies)

emoji_counts = (emojies_df_telur2
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

   Emoji  Count
0      🍚      1
1      ☀      1
2      😉      1
3      ✋      1
4      🔹      1
5      😜      1
6     ✌️      1
7      📎      1
8      📌      1
9      🍵      1
10     🔺      1
11     😂      1
12     ✨      1
13     🔪      1
14     🌻      1
15     🍳      2
16     🍅      2
17     ⚪      2
18     ⚫      2
19     🍃      2
20     🥙      2
21     😅      2
22     ▶      2
23     😊      2
24     🍝      2
25     ♨      2
26     💞      2
27     🌶      3
28     🍀      3
29     😋      3
30     🥚      3
31     🍘      3
32     📝      3
33     😍      4
34     🐣      4
35     ❤      4
36     🌀      4
37     ✔      6
38     👇      6
39     👉      6
40     🌸      8
41     😁      8

In [ ]:
df_telur['Ingredients'] = df_telur['Ingredients'].str.replace('[^a-zA-z0-9.,!?/:;\"\'\s]', '', flags=re.UNICODE)
df_telur['Ingredients']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

0       1 buah telur10 buncis3 bawang merah2 bawang pu...
1       4 sayap ayam4 buah telor1/2 papan tempeBumbu h...
2       1/2 kaleng kornet23 buah bawang prei2 buah tel...
3       1 butir telur1 potong tahu putih goreng seteng...
4       4 butir telur4 siung bwng merah2 siung bwng pu...
                              ...
1969    6 butir telur10 grm paprika kuning2 sendok mkn...
1970    1 papan tempe, kukus1 butir telur ayam1 batang...
1971    5 buah telur rebus yg telah dikupas1 buah teh ...
1972    2 buah tomat1 potong tahu halus nen tofu4 buti...
1973    3 Butir Telur, kocok lepas3 Siung Bawang merah...
Name: Ingredients, Length: 1974, dtype: object

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_telur2c = df_telur['Ingredients'].apply(extract_emojies)

emoji_counts = (emojies_df_telur2c
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_telur3 = df_telur['URL'].apply(extract_emojies)

emoji_counts = (emojies_df_telur3
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
df_tempe = pd.read_csv("dataset-tempe.csv")

In [ ]:
df_tempe

,Title,Ingredients,URL
0,Orek tempe manis pedas super simple,Tempe (saya beli 3000 saja)--3 buah cabe gendo...,/id/resep/4474061-orek-tempe-manis-pedas-super...
1,Terik ayam tempe telor,4 sayap ayam--4 buah telor--1/2 papan tempe--B...,/id/resep/4474066-terik-ayam-tempe-telor
2,Penyet Tempe Sambel Korek Kemangi,2 buah tempe--1 genggam Daun kemangi--15 cabe ...,/id/resep/4473809-penyet-tempe-sambel-korek-ke...
3,Nugget tempe,1 papan tempe dihaluskan(saya kukus dlu)--1 bu...,/id/resep/4473715-nugget-tempe
4,Tempe tepung sajiku,1 potong tempe 3000--1 bngkus sajiku tepung se...,/id/resep/4473463-tempe-tepung-sajiku
...,...,...,...
1981,Tempe mendol jawa timur,1 papan tempe--2 bawang putih--4 bawang merah-...,/id/resep/3944154-tempe-mendol-jawa-timur
1982,Tempe goreng gurih,1 papan tempe--2-3 siung bawang putih--+ 1cm k...,/id/resep/3944200-tempe-goreng-gurih
1983,Oseng tempe Lombok ijo,1/4 papan tempe--11 Lombok ijo--1 cabe rawit m...,/id/resep/3943987-oseng-tempe-lombok-ijo
1984,Tahu tempe bumbu kuning,Tahu--Tempe--Bumbu:--2 bawang putih--4 bawang ...,/id/resep/3943872-tahu-tempe-bumbu-kuning
1985,Keripik tempe,500 gram bakal tempe--300 gram tepung tapioka-...,/id/resep/3942205-keripik-tempe

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_tempe1 = df_tempe['Title'].apply(extract_emojies)

emoji_counts = (emojies_df_tempe1
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

   Emoji  Count
0      🍌      1
1      😊      1
2      🌶      1
3      😬      1
4      😉      1
5      🦈      1
6      🍡      1
7      🐔      1
8      🍤      1
9      💕      1
10     ❤      1
11     👉      1
12     👅      1
13     👌      1
14     🌴      1
15     💞      1
16     👈      1
17     🐓      1
18     🌸      1
19    ❤️      2
20     😀      2
21     😍      2
22     😛      2
23     😆      2
24    🇮🇩      2
25     🍔      2
26     🐟      2
27     🍛      3
28     😅      3
29     😂      4
30     💓      4
31     🔥      4
32     😄      4
33    👍🏾      4
34     😁      6
35     😘      7
36     👍      8
37     😋     11

In [ ]:
df_tempe['Title'] = df_tempe['Title'].str.replace('[^a-zA-z0-9.,!?/:;\"\'\s]', '', flags=re.UNICODE)
df_tempe['Title']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

0       Orek tempe manis pedas super simple
1                    Terik ayam tempe telor
2         Penyet Tempe Sambel Korek Kemangi
3                              Nugget tempe
4                       Tempe tepung sajiku
                       ...
1981                Tempe mendol jawa timur
1982                     Tempe goreng gurih
1983                 Oseng tempe Lombok ijo
1984                Tahu tempe bumbu kuning
1985                          Keripik tempe
Name: Title, Length: 1986, dtype: object

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_tempe1c = df_tempe['Title'].apply(extract_emojies)

emoji_counts = (emojies_df_tempe1c
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
df_tempe['Ingredients']= df_tempe['Ingredients'].astype(str)

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_tempe2 = df_tempe['Ingredients'].apply(extract_emojies)

emoji_counts = (emojies_df_tempe2
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

   Emoji  Count
0      🌿      1
1      🐣      1
2      🔷      1
3      ✨      1
4      ⏬      1
5      🐴      1
6      😬      1
7      😉      1
8      🍉      1
9      🍁      1
10     😃      1
11     😁      1
12     😅      1
13     💋      1
14     😂      1
15     📣      1
16     😍      1
17     😆      1
18     🐔      1
19     🍄      1
20     🌾      1
21     👉      1
22     💠      2
23     🍅      2
24     😀      2
25     🌸      2
26     🐾      2
27     ☘      2
28     🍘      2
29     🌰      2
30     🍲      2
31     🍭      3
32     😊      3
33     🔪      3
34     🍀      3
35     😱      3
36     🌵      3
37     ▶      3
38     ✔      3
39     💞      4
40     🌻      4
41     🍃      5
42     🍂      6
43     ♥      6
44     🍥      6
45     🌀      6
46     🎯      6
47     👇      9
48     🌶     12
49     ❤     19

In [ ]:
df_tempe['Ingredients'] = df_tempe['Ingredients'].str.replace('[^a-zA-z0-9.,!?/:;\"\'\s]', '', flags=re.UNICODE)
df_tempe['Ingredients']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

0       Tempe saya beli 3000 saja3 buah cabe gendot3 b...
1       4 sayap ayam4 buah telor1/2 papan tempeBumbu h...
2       2 buah tempe1 genggam Daun kemangi15 cabe rawi...
3       1 papan tempe dihaluskansaya kukus dlu1 buah w...
4       1 potong tempe 30001 bngkus sajiku tepung serb...
                              ...
1981    1 papan tempe2 bawang putih4 bawang merah4 cab...
1982    1 papan tempe23 siung bawang putih 1cm kunyitS...
1983    1/4 papan tempe11 Lombok ijo1 cabe rawit merah...
1984    TahuTempeBumbu:2 bawang putih4 bawang merah3 k...
1985    500 gram bakal tempe300 gram tepung tapioka5 s...
Name: Ingredients, Length: 1986, dtype: object

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_tempe2c = df_tempe['Ingredients'].apply(extract_emojies)

emoji_counts = (emojies_df_tempe2c
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_tempe3 = df_tempe['URL'].apply(extract_emojies)

emoji_counts = (emojies_df_tempe3
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
df_udang = pd.read_csv("dataset-udang.csv")

In [ ]:
df_udang

,Title,Ingredients,URL
0,Lumpia udang kulit tahu ala fe',50 gram ayam potong kotak kecil--200 gram udan...,/id/resep/4448366-lumpia-udang-kulit-tahu-ala-fe
1,Bakso Ayam Udang Keto,400 gr ayam giling--250 gr udang kupas--3 telu...,/id/resep/4474544-bakso-ayam-udang-keto
2,Udang ala pop corn,1/4 kg udang basah ukuran sedang--1 bungkus ko...,/id/resep/4418156-udang-ala-pop-corn
3,Bakwan Udang Sederhana,1/2 kg Tepung terigu (sudah di ayak)--1/2 Udan...,/id/resep/4475500-bakwan-udang-sederhana
4,Udang Goreng Tepung Mayonaise,300 gr udang (buang kepalanya)--Jeruk nipis--T...,/id/resep/4474156-udang-goreng-tepung-mayonaise
...,...,...,...
1989,Udang saus mentega,1 kg udang segar--1 buah bawang bombay kecil--...,/id/resep/3794442-udang-saus-mentega
1990,Jipang tumis udang,500 gr jipang(saya pk 6bh jipang muda yg kecil...,/id/resep/3795267-jipang-tumis-udang
1991,Tumis Udang Tempe,3 siung bawang merah--3 siung bawang putih--2 ...,/id/resep/3794945-tumis-udang-tempe
1992,Tumis kacang panjang terong udang,"Stgah ikat kacang panjang,ku bli 3ribu d psr--...",/id/resep/3794623-tumis-kacang-panjang-terong-...
1993,Siomay Udang Ayam,3 bh dada ayam--1/2 kg udang bersih--6 bh bawa...,/id/resep/3794009-siomay-udang-ayam

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_udang1 = df_udang['Title'].apply(extract_emojies)

emoji_counts = (emojies_df_udang1
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

   Emoji  Count
0      🍜      1
1      😉      1
2      😎      1
3      🍄      1
4      😬      1
5      🍳      1
6      🔥      1
7      🍴      1
8      🍍      1
9      🦁      1
10     🍛      1
11     🍟      1
12     🍆      1
13    🌶️      1
14     🤗      1
15     🥕      1
16     🍯      1
17     🌹      1
18   👩‍🍳      1
19     😍      2
20    💪🏻      2
21     💓      2
22     😚      2
23     👍      2
24     👌      2
25     😆      2
26     🌶      2
27     😘      2
28     🍲      3
29     😊      3
30     😂      5
31     😁      5
32     🦐      6
33     😋      9
34     🍤     30

In [ ]:
df_udang['Title'] = df_udang['Title'].str.replace('[^a-zA-z0-9.,!?/:;\"\'\s]', '', flags=re.UNICODE)
df_udang['Title']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

0         Lumpia udang kulit tahu ala fe'
1                   Bakso Ayam Udang Keto
2                      Udang ala pop corn
3                  Bakwan Udang Sederhana
4           Udang Goreng Tepung Mayonaise
                      ...
1989                   Udang saus mentega
1990                   Jipang tumis udang
1991                    Tumis Udang Tempe
1992    Tumis kacang panjang terong udang
1993                    Siomay Udang Ayam
Name: Title, Length: 1994, dtype: object

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_udang1c = df_udang['Title'].apply(extract_emojies)

emoji_counts = (emojies_df_udang1c
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_udang2 = df_udang['Ingredients'].apply(extract_emojies)

emoji_counts = (emojies_df_udang2
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

   Emoji  Count
0      😢      1
1      🍡      1
2      😑      1
3      😀      1
4      🌰      1
5      💕      1
6      🍒      1
7      💋      1
8      😝      1
9      💮      1
10     😆      1
11     😅      1
12     ❤      1
13     💜      2
14     💚      2
15     🌶      2
16     🍁      2
17     🍭      2
18     🌿      2
19     🥗      2
20     📌      3
21     ♨      3
22     😂      4
23     😁      4
24     😘      5
25     ▶      6
26     🌀      6
27     ✨      7
28     👇      9
29     🌸      9
30     👉     10
31     🦐     17
32     🍤     18

In [ ]:
df_udang['Ingredients'] = df_udang['Ingredients'].str.replace('[^a-zA-z0-9.,!?/:;\"\'\s]', '', flags=re.UNICODE)
df_udang['Ingredients']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

0       50 gram ayam potong kotak kecil200 gram udang ...
1       400 gr ayam giling250 gr udang kupas3 telur ay...
2       1/4 kg udang basah ukuran sedang1 bungkus kobe...
3       1/2 kg Tepung terigu sudah di ayak1/2 Udang se...
4       300 gr udang buang kepalanyaJeruk nipisTepung ...
                              ...
1989    1 kg udang segar1 buah bawang bombay kecil4 si...
1990    500 gr jipangsaya pk 6bh jipang muda yg kecil,...
1991    3 siung bawang merah3 siung bawang putih2 buah...
1992    Stgah ikat kacang panjang,ku bli 3ribu d psrTe...
1993    3 bh dada ayam1/2 kg udang bersih6 bh bawang p...
Name: Ingredients, Length: 1994, dtype: object

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_udang2c = df_udang['Ingredients'].apply(extract_emojies)

emoji_counts = (emojies_df_udang2c
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_udang3 = df_udang['URL'].apply(extract_emojies)

emoji_counts = (emojies_df_udang3
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
from google.colab import files

df_ayam.to_csv('clean_df_ayam.csv', encoding = 'utf-8-sig') 
files.download('clean_df_ayam.csv')

In [ ]:
df_testing = pd.read_csv("clean_df_ayam.csv")

In [ ]:
df_testing

,Unnamed: 0,Title,Ingredients,URL
0,0,Ayam Woku Manado,1 Ekor Ayam Kampung potong 122 Buah Jeruk Nipi...,/id/resep/4473027-ayam-woku-manado
1,1,Ayam goreng tulang lunak,1 kg ayam dipotong sesuai selera jangan kecil2...,/id/resep/4471956-ayam-goreng-tulang-lunak
2,2,Ayam cabai kawin,1/4 kg ayam3 buah cabai hijau besar7 buah caba...,/id/resep/4473057-ayam-cabai-kawin
3,3,Minyak Ayam,400 gr kulit ayam lemaknya8 siung bawang puti...,/id/resep/4427438-minyak-ayam
4,4,Nasi Bakar Ayam,"1 piring nasi/ fillet ayam, potong kotak, cuci...",/id/resep/4472552-nasi-bakar-ayam
...,...,...,...,...
1790,1790,Nugget ayam simpel,400 gram ayam giling1 lembar roti tawar kupas2...,/id/resep/4308989-nugget-ayam-simpel
1791,1791,Ukepan Ayam,1/2 kg ayam6 siung bawang merah6 siung bawang ...,/id/resep/4289253-ukepan-ayam
1792,1792,Chicken Stroganoff with Mushroom,"Fillet ayam, cuci bersih lumuri sedikit tepun...",/id/resep/4308032-chicken-stroganoff-with-mush...
1793,1793,Sop Pangsit Ayam,1/4 kg dada ayam1 buah jeruk nipis2 cm Jahe ge...,/id/resep/4308088-sop-pangsit-ayam
1794,1794,Ayam Bumbu Bawang,"1 dada ayam fillet, cuci bersih, potong kecil2...",/id/resep/4308575-ayam-bumbu-bawang

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_testing1 = df_testing['Title'].apply(extract_emojies)

emoji_counts = (emojies_df_testing1
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
df_testing['Ingredients']= df_testing['Ingredients'].astype(str)

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_testing2 = df_testing['Ingredients'].apply(extract_emojies)

emoji_counts = (emojies_df_testing2
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []

In [ ]:
def extract_emojies(x):
  doc = nlp(x)
  emojis = [token.text for token in doc if token._.is_emoji]
  
  return emojis

emojies_df_testing3 = df_testing['URL'].apply(extract_emojies)

emoji_counts = (emojies_df_testing3
                .apply(pd.Series) #breaks up the list into seperate columns 
                .stack() #collapses each column into one column
                .value_counts() #counts the frequency of each item
                .rename('Count')
                .sort_values()
                .reset_index()
                .rename(columns={'index':'Emoji'}))
emoji_counts

Empty DataFrame
Columns: [Emoji, Count]
Index: []